### ISSUE TITLE
Make clear that the node also supports F200 - SR300 cameras

### ISSUE THREAD

**Issue by severin-lemaignan** [intel-ros/realsense#1]
Great to see official ROS support for the RealSense cameras.

While the node supports the F200 and SR300 cameras as well, it is not very obvious.

The documentation should mention it, and the launch files should not be named `*_r200_*` as they are not R200 specific.

**Comment by mkhansen-intel** [comment]
Yes! Our first release was really only for R200, but we'll add support for F200 and SR300 soon. We'll post an update to the issue when we do.

**Comment by mkhansen-intel** [comment]
We currently are only supporting the R200 camera, we'll update the launch files and documentation when the other cameras are supported.

**Comment by severin-lemaignan** [comment]
Thanks for the feedback.

You still may want to clarify the documentation and leave this issue open (possibly renaming it 'Support for F200-SR300) so that other users know what to expect and can easily monitor the progress.
