### ISSUE TITLE
State explicitly whether this needs UVC or V4L backend for librealsense.

### ISSUE THREAD

**Issue by peci1** [intel-ros/realsense#16]
I think the readme should contain this kind of information in the install section.

**Comment by mkhansen-intel** [comment]
This was discussed internally and we have no code in this ROS package that is specific to V4L or UVC, so we don't believe the readme file should restrict or document a requirement for one or the other. We think this should be part of the librealsense readme which it is.

**Comment by peci1** [comment]
What about explicitly stating it works with both? :)

**Comment by mkhansen-intel** [comment]
OK, we're going to update the BKC in a future release to show that we're testing with the V4L backend.

**Comment by mkhansen-intel** [comment]
This is now part of our BKC. I'm closing this issue.
