### ISSUE TITLE
Parent link stays as "camera_link" even after changing the camera parameter

### ISSUE THREAD

**Issue by mirzashah** [intel-ros/realsense#21]
When running two instances of realsense_r200_rgbd.launch simultaneously, both cameras retain the parent link of "camera_link" for the rgb and optical frames.

 e.g. If you set camera:=camera1, the rgb and depth links will be camera1_rgb_frame and camera1_depth_frame, but the parent link will be camera_link instead of camera1_link.

**Comment by reaganlo** [comment]
@mirzashah Thanks for the update. We will look into this.

**Comment by mirzashah** [comment]
It seems I was mistaken -- after a reboot the TF tree looks correct -- sorry for the mistake.
