### ISSUE TITLE
error roslaunch realsense_camera realsense_r200_nodelet_standalone_preset.launch

### ISSUE THREAD

**Issue by WeJay** [intel-ros/realsense#37]
### System Configuration
Please complete Your Configuration detail below.

| Version          | Best Known           | Your Configuration   |
|:---------------- |:---------------------|:---------------------|
| Operating System | Ubuntu 14.04.4 LTS   | Ubuntu 14.04.4 LTS                |
| Kernel           | 4.4.0-040400-generic | 4.4.0-040400-generic |
| Backend          | video4linux          | Video4Linux backend                  |
| ROS              | indigo               | indigo                   |
| ROS RealSense    | Latest Release       | Latest Release               |
| librealsense     | 0.9.1                |  0.9.1                |
| R200 Firmware    | 1.0.72.06            | 1.0.72.06              |

---
HI! I'm Wejay
I have same problem like issue #26,I'm not really good at linux,please tell me how to solve this 
problem.
And I can not run cpp-capture by command line,but running within QT creator works.
It shows:
RealSense error calling rs_create_context(api_version:4):
uvc_open2(...) returned Access denied
In [https://github.com/IntelRealSense/librealsense/issues/81](url),I really can not understand how to fix this problem.
![2016-05-09 20 51 20](https://cloud.githubusercontent.com/assets/17249978/15113670/49180b68-1628-11e6-8ca2-f2d66f1e7fe6.png)

**Comment by mdhorn** [comment]
Yes, this looks exactly like #26.

Did you attempt the solution noted?

Try adding your login account to the group `video`.

`sudo adduser $USER video`

You may need to log out and log back into the system to see the new group.

`groups`

In general, the video devices will be owned by `root` and set to group `video`:

```
$ ls -l /dev/video*
crw-rw----+ 1 root video 81, 3 Apr 12 18:02 /dev/video3
crw-rw----+ 1 root video 81, 4 Apr 12 18:02 /dev/video4
crw-rw----+ 1 root video 81, 5 Apr 12 18:02 /dev/video5
```

**Comment by WeJay** [comment]
I have attempted the solution noted. But I can not still solve my problem. 

after I  do ,
$ ls -l /dev/video*
crw-rw----+ 1 root video 81, 0  5月 10 16:45 /dev/video0
crw-rw----+ 1 root video 81, 1  5月 10 16:45 /dev/video1
crw-rw----+ 1 root video 81, 2  5月 10 16:45 /dev/video2
crw-rw----+ 1 root video 81, 3  5月 10 16:45 /dev/video3

**Comment by mdhorn** [comment]
Did you try logging out and logging back in after making the group change?
The group membership only takes effect on login.

**Comment by WeJay** [comment]
I tried your steps. Then, I can't still solve. 
I can not launch cpp-capture.launch.
My result show
![2016-05-12 17 49 44](https://cloud.githubusercontent.com/assets/17249978/15210646/f2fa887a-1869-11e6-9ebc-3da673ffe112.png)


but running within QT creator works. show 

![2016-05-09 19 42 38](https://cloud.githubusercontent.com/assets/17249978/15210670/0a98b8ee-186a-11e6-991c-44d26c5d7cae.png)

**Comment by mdhorn** [comment]
The fact that cpp-capture is failing in rs_create_context would imply that something is holding or not release the device.

In this issue you stated that you are using Video4Linux backend and NOT libuvc; can you please confirm that. It looks more like your problem is similar to https://github.com/IntelRealSense/librealsense/issues/81 where libuvc was in use. 

Can you confirm you are aren't using libuvb (which we don't support):
`dpkg -l | grep libuvc`
And that you have a current and/or patch kernel?
`uname -a`

**Comment by WeJay** [comment]
sorry , I'm not really good at linux. 
Thank for your patient to teach me step by step.
![problem1](https://cloud.githubusercontent.com/assets/17249978/15293483/c0e9bf0a-1bba-11e6-93e2-0995cf796b55.png)

I  install by below 
https://github.com/IntelRealSense/librealsense/blob/master/doc/installation.md#video4linux-backend

I install both Video4Linux backend and LibUVC backend.

As problem IntelRealSense/librealsense#81, I need remove LibUVC backend?

How can i do ?

**Comment by mdhorn** [comment]
Okay, there is the problem; the directions are an either/or, not both. When you did the second install following the directions for libuvc, you replaced the librealsense library with the libuvc version which we don't support.

Repeat the installation steps for "Video4Linux backend".

**Comment by WeJay** [comment]
When I repeat the installation steps for "Video4Linux backend", it shows they exist. Then,I can not install again.

Should I change the file name , v4.4-wily , to v4.5-wily ?

Or how can I solve the problem?

Thank you.

**Comment by mdhorn** [comment]
The kernel portion should already be installed.

Just change directory (cd) to where you you put librealsense source
`cd` *\<librealsense\>*
`make clean`
`make && sudo make install`

**Comment by WeJay** [comment]
Hi , I have three problem.

> Problem1
I run `sudo dmesg | tail -n 50` after I repeat the installation steps for "Video4Linux backend" . 
It shows "failed to excute"
![problem5](https://cloud.githubusercontent.com/assets/17249978/15397929/6925f034-1e14-11e6-9eb2-e835fa951124.png)
How do I solve?
However , I can run cpp-capture.

> Problem 2 
I run `roslaunch turtlebot_bringup `minimal.launch`.
Then I meet this problem.
![problem6](https://cloud.githubusercontent.com/assets/17249978/15398220/69475f3e-1e15-11e6-82ce-26707c2c322f.png)
![problem9](https://cloud.githubusercontent.com/assets/17249978/15398234/6e306068-1e15-11e6-93ee-e7e4784b715a.png)
This turtlebot_state is error.

> Problem3 
I run `roslaunch realsense_camera realsense_r200_navigation.launch`.
![problem7](https://cloud.githubusercontent.com/assets/17249978/15398322/c14430fe-1e15-11e6-8eb0-ea9bee2e8b31.png)
The device R200 can light.
But I run `roslaunch realsense_navigation gmapping.launch`.
![problem8](https://cloud.githubusercontent.com/assets/17249978/15398367/eb9efc9e-1e15-11e6-9cba-65f7fed6e364.png)
It shows 0 device connected.

Sorry , help me solve problems.

Thank you.

**Comment by mdhorn** [comment]
It appears you got the RealSense ROS node working.

For the navigation example, did you follow all of the directions in the [README.md](https://github.com/intel-ros/realsense/blob/indigo-devel/camera/navigation/turtlebot/README.md)?
