### ISSUE TITLE
Service call failed! in odd number runs

### ISSUE THREAD

**Issue by ZahraBoroujeni** [intel-ros/realsense#43]
### System Configuration
Please complete Your Configuration detail below.

| Version          | Best Known           | Your Configuration   |
|:---------------- |:---------------------|:---------------------|
| Operating System | Ubuntu 14.04.4 LTS   | Ubuntu 14.04.4 LTS |
| Kernel           | 4.4.0-040400-generic | 3.10.96+               |
| Backend          | video4linux          | video4linux                    |
| ROS              | indigo               | indigo                    |
| ROS RealSense    | Latest Release       | 1.0.3               |
| librealsense     | 0.9.1                |0.9.1              |
| R200 Firmware    | 1.0.72.06            | 3.10.10.0            |

---

### Expected Behavior
I want to run realsense_camera_nodelet on odroid xu4, Samsung Exynos5422 ARM® Cortex™-A15 Quad 2.0GHz/Cortex™-A7 Quad 1.4GHz. I am using SR300 camera. I used the package for sr300 from here:
https://github.com/nlyubova/realsense
and librealsense library for ARM from here:
https://github.com/Maghoumi/librealsense 
 I reduce fps to 30.  
### Actual Behavior
Every time that I run the node for the first time it crashed, and I received Error below, but second time it run without error, and alternatively once time it crashes and the other time it runs successfully :
```
[FATAL] [1356999608.372189726]: Service call failed!
[SR300_nodelet_manager-2] process has died [pid 10925, exit code -11, cmd /opt/ros/indigo/lib/nodelet/nodelet manager __name:=SR300_nodelet_manager __log:=/root/.ros/log/fa7186aa-53a8-11e2-bf31-7cdd908e0595/SR300_nodelet_manager-2.log].
log file: /root/.ros/log/fa7186aa-53a8-11e2-bf31-7cdd908e0595/SR300_nodelet_manager-2*.log
[camera_nodelet-3] process has died [pid 10931, exit code 255, cmd /opt/ros/indigo/lib/nodelet/nodelet load realsense_camera/RealsenseNodelet SR300_nodelet_manager rgb/image_raw:=app/camera/rgb/image_raw camera/depth/image_raw:=depth/image_raw camera/color/image_raw:=rgb/image_raw camera/infrared1/image_raw:=ir/image_raw camera/infrared2/image_raw:=ir2/image_raw camera/depth/points:=depth/points camera/depth/camera_info:=depth/camera_info camera/color/camera_info:=rgb/camera_info camera/infrared1/camera_info:=ir/camera_info camera/infrared2/camera_info:=ir2/camera_info __name:=camera_nodelet __log:=/root/.ros/log/fa7186aa-53a8-11e2-bf31-7cdd908e0595/camera_nodelet-3.log].
log file: /root/.ros/log/fa7186aa-53a8-11e2-bf31-7cdd908e0595/camera_nodelet-3*.log
```

Do you have any idea? I think some where we should add waitforSerivce line, but I don't know where.
### Steps to Reproduce

I can run the roslaunch successfully using line below:

```
timeout 10 roslaunch realsense_camera realsense_sr300.launch
roslaunch realsense_camera realsense_sr300.launch 
```

**Comment by mdhorn** [comment]
We are not yet support SR300 in the the mainline code. Support is in the queue and is prioritized, but it doesn't currently existing on the official release.

I'd suggest upgrading your kernel to a 4.4.x release. The [librealsense](https://github.com/IntelRealSense/librealsense/blob/master/doc/installation.md) direction discourage the use of the 3.19 kernel with patches and you are at 3.10.
