### ISSUE TITLE
Refactor code to easily support additional cameras

### ISSUE THREAD

**Issue by mdhorn** [intel-ros/realsense#48]
### System Configuration

| Version          | Your Configuration   |
|:---------------- |:---------------------|
| Operating System | Ubuntu 16.04 LTS   |
| Kernel           | 4.4.0-22-generic |
| Backend          | video4linux  |
| ROS              | kinetic  |
| ROS RealSense    | 1.1.0  |
| librealsense     | v0.9.2  |
| R200 Firmware    | 1.0.72.06  |

### Details
Refactor the current code to make it easier to extend to additional RealSense cameras.
Suggest creating a core, base camera class and then extended it for the R200.

**Comment by mkhansen-intel** [comment]
This is in progress...

**Comment by mdhorn** [comment]
Fixed in Release 1.2.0
