### ISSUE TITLE
xyzrgb point cloud freezes in rviz after displaying for 15 seconds 

### ISSUE THREAD

**Issue by jgoppert** [intel-ros/realsense#55]
This is a regression on issue #25

**Comment by mdhorn** [comment]
Can we get you current configuration details?

Please complete Your Configuration detail below. Refer to the BKC at [Configuration](../realsense_camera/README.md#configuration).

| Version | Your Configuration |
| :-- | :-- |
| Operating System | ? ? ? |
| Kernel | ?-?-? |
| Backend | ? |
| ROS | ? |
| ROS RealSense | ?.?.? |
| librealsense | ?.?.? |
| R200 Firmware | ?.?.?.? |
| HW CPU model and number | ? |
| RAM | ? |

**Comment by jgoppert** [comment]
I can't reproduce this anymore. Closing.
