### ISSUE TITLE
problem cpp-capture example : rs.warn: Subdevice 1 bad magic number 0x0

### ISSUE THREAD

**Issue by won13y** [intel-ros/realsense#57]
I have the following issue when trying to use a R200 with librealsense:

it works as following figures:

![screenshot from 2016-06-23 16 41 30](https://cloud.githubusercontent.com/assets/13333754/16295414/c89a05c4-3961-11e6-8092-516012492326.png)

COLOR image is correctly shown, 

but detph / infrared1/infrared 2 image are not enabled, and are shown as black

wkyoun@wkyoun-15Z960-GA70K:~/librealsense-stable/bin$ ./cpp-capture 

    Capturing DEPTH at 480 x 360, fov = 56.2 x 43.6, distortion = NONE
    Capturing COLOR at 640 x 480, fov = 54.5 x 41.9, distortion = MODIFIED_BROWN_CONRADY
    Capturing INFRARED at 480 x 360, fov = 56.2 x 43.6, distortion = NONE
    Capturing INFRARED2 at 480 x 360, fov = 56.2 x 43.6, distortion = NONE
    rs.warn: Subdevice 0 bad magic number 0x260025
    rs.warn: Subdevice 1 bad magic number 0x0
    rs.warn: Subdevice 0 bad magic number 0x230026
    rs.warn: Subdevice 1 bad magic number 0x0
    rs.warn: Subdevice 0 bad magic number 0x290024
    rs.warn: Subdevice 1 bad magic number 0x0
    rs.warn: Subdevice 0 bad magic number 0x29002f
    rs.warn: Subdevice 1 bad magic number 0x0
    rs.warn: Subdevice 0 bad magic number 0x1250108
    rs.warn: Subdevice 1 bad magic number 0x0
    rs.warn: Subdevice 0 bad magic number 0x1380139
    rs.warn: Subdevice 1 bad magic number 0x0
    rs.warn: Subdevice 0 bad magic number 0x14b0137
    rs.warn: Subdevice 1 bad magic number 0x0
    rs.warn: Subdevice 0 bad magic number 0x140013b
    rs.warn: Subdevice 1 bad magic number 0x0
    rs.warn: Subdevice 0 bad magic number 0x1380146
    rs.warn: Subdevice 1 bad magic number 0x0

sudo dmesg | tail -n 50 command result in following

wkyoun@wkyoun-15Z960-GA70K:~/librealsense-stable/bin$ sudo dmesg | tail -n 50

    [ 4457.046735] input: Intel RealSense 3D Camera R200 as /devices/pci0000:00/0000:00:14.0/usb2/2-1/2-1:1.4/input/input29
    [ 4457.213421] uvcvideo: Found UVC 1.00 device LG HD WebCam (2232:5008)
    [ 4457.215481] input: LG HD WebCam as /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6:1.0/input/input30
    [ 4457.222238] uvcvideo: Unknown video format 49323159-0000-0010-8000-00aa00389b71
    [ 4457.222247] uvcvideo: Unknown video format 20493859-0000-0010-8000-00aa00389b71
    [ 4457.222256] uvcvideo: Found UVC 1.10 device Intel RealSense 3D Camera R200 (8086:0a80)
    [ 4457.263339] uvcvideo: Unknown video format 2036315a-0000-0010-8000-00aa00389b71
    [ 4457.263367] uvcvideo: Found UVC 1.10 device Intel RealSense 3D Camera R200 (8086:0a80)
    [ 4457.267106] uvcvideo: Unable to create debugfs 2-4 directory.
    [ 4457.268395] input: Intel RealSense 3D Camera R200 as /devices/pci0000:00/0000:00:14.0/usb2/2-1/2-1:1.2/input/input31
    [ 4457.362164] uvcvideo: Unknown video format 30315752-0000-0010-8000-00aa00389b71
    [ 4457.362182] uvcvideo: Found UVC 1.10 device Intel RealSense 3D Camera R200 (8086:0a80)
    [ 4457.367833] uvcvideo: Unable to create debugfs 2-4 directory.
    [ 4457.369267] input: Intel RealSense 3D Camera R200 as /devices/pci0000:00/0000:00:14.0/usb2/2-1/2-1:1.4/input/input32
    [ 4636.125445] uvcvideo: Non-zero status (-71) in video completion handler.
    [ 4750.332679] uvcvideo: Non-zero status (-71) in video completion handler.
    [ 4750.341494] uvcvideo: Non-zero status (-71) in video completion handler.
    [ 4750.351163] uvcvideo: Non-zero status (-71) in video completion handler.
    [ 4767.050127] systemd-hostnamed[7288]: Warning: nss-myhostname is not installed. Changing the local hostname might make it unresolveable. Please install nss-myhostname!
    [ 7309.098505] usbcore: deregistering interface driver uvcvideo
    [ 7430.853682] media: Linux media interface: v0.10
    [ 7430.859091] Linux video capture interface: v2.00
    [ 7430.951182] uvcvideo: Found UVC 1.00 device LG HD WebCam (2232:5008)
    [ 7430.953611] input: LG HD WebCam as /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6:1.0/input/input33
    [ 7431.037235] uvcvideo: Unknown video format 49323159-0000-0010-8000-00aa00389b71
    [ 7431.037252] uvcvideo: Unknown video format 20493859-0000-0010-8000-00aa00389b71
    [ 7431.037268] uvcvideo: Found UVC 1.10 device Intel RealSense 3D Camera R200 (8086:0a80)
    [ 7431.040997] uvcvideo: Unknown video format 2036315a-0000-0010-8000-00aa00389b71
    [ 7431.041022] uvcvideo: Found UVC 1.10 device Intel RealSense 3D Camera R200 (8086:0a80)
    [ 7431.042912] uvcvideo: Unable to create debugfs 2-4 directory.
    [ 7431.043529] input: Intel RealSense 3D Camera R200 as /devices/pci0000:00/0000:00:14.0/usb2/2-1/2-1:1.2/input/input34
    [ 7431.045414] uvcvideo: Unknown video format 30315752-0000-0010-8000-00aa00389b71
    [ 7431.045435] uvcvideo: Found UVC 1.10 device Intel RealSense 3D Camera R200 (8086:0a80)
    [ 7431.047256] uvcvideo: Unable to create debugfs 2-4 directory.
    [ 7431.047705] input: Intel RealSense 3D Camera R200 as /devices/pci0000:00/0000:00:14.0/usb2/2-1/2-1:1.4/input/input35
    [ 7431.048918] usbcore: registered new interface driver uvcvideo
    [ 7431.048929] USB Video Class driver (1.1.1)
    [ 7431.151828] uvcvideo: Found UVC 1.00 device LG HD WebCam (2232:5008)
    [ 7431.157193] input: LG HD WebCam as /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6:1.0/input/input36
    [ 7431.170372] uvcvideo: Unknown video format 49323159-0000-0010-8000-00aa00389b71
    [ 7431.170396] uvcvideo: Unknown video format 20493859-0000-0010-8000-00aa00389b71
    [ 7431.170423] uvcvideo: Found UVC 1.10 device Intel RealSense 3D Camera R200 (8086:0a80)
    [ 7431.224245] uvcvideo: Unknown video format 2036315a-0000-0010-8000-00aa00389b71
    [ 7431.224255] uvcvideo: Found UVC 1.10 device Intel RealSense 3D Camera R200 (8086:0a80)
    [ 7431.226607] uvcvideo: Unable to create debugfs 2-4 directory.
    [ 7431.226758] input: Intel RealSense 3D Camera R200 as /devices/pci0000:00/0000:00:14.0/usb2/2-1/2-1:1.2/input/input37
    [ 7431.265523] uvcvideo: Unknown video format 30315752-0000-0010-8000-00aa00389b71
    [ 7431.265531] uvcvideo: Found UVC 1.10 device Intel RealSense 3D Camera R200 (8086:0a80)
    [ 7431.267786] uvcvideo: Unable to create debugfs 2-4 directory.
    [ 7431.268090] input: Intel RealSense 3D Camera R200 as /devices/pci0000:00/0000:00:14.0/usb2/2-1/2-1:1.4/input/input38

It seems to me that there are similar problems reported like mine, but I cannot see any clear solutions.

Last question is following

would you please let me know how to find the Firmware Version of R200 that I am using?

**Comment by ddiakopoulos** [comment]
This is an installation issue on your Ubuntu system. Please refer to the issue you created on the librealsense repo for resolution (you need to follow the installation.md more closely): https://github.com/IntelRealSense/librealsense/issues/183

**Comment by mdhorn** [comment]
Appears to be tracked in librealsense.
Closing.
