### ISSUE TITLE
proportional-to-distance mean error of depth measurements

### ISSUE THREAD

**Issue by imbachb** [intel-ros/realsense#58]
### System Configuration

| Version | Your Configuration |
| :-- | :-- |
| Operating System | Ubuntu 14.04.4 LTS |
| Kernel | 4.4.0-040400-generic |
| Backend | video4linux |
| ROS | indigo |
| ROS RealSense | 1.0.4 |
| librealsense | 0.9.1 |
| R200 Firmware | 1.0.72.06 |

I'm currently trying to use the R200 on a quadrocopter for 3D map generation. Something that I observed is that the (or my) R200 seems to have a mean error in depth measurements  that is dependent on the measured distance. The following maps were generated while moving the quadrocopter slowly towards a wall. In the first image you can clearly see how the wall shifts forward when the quadrotor gets nearer (i.e. mean error gets smaller). In the second image I used a quadratic function of measured distance to subtract the mean error.

![without_sensor_model_top1](https://cloud.githubusercontent.com/assets/13905978/16300606/11935d6e-3941-11e6-984d-e89dad984f62.png) ![with_sensor_model_top1](https://cloud.githubusercontent.com/assets/13905978/16300605/11933d0c-3941-11e6-98e8-329ded45c749.png)

The subtraction of the mean error works fairly well. I'm just wondering whether this is a problem of my R200 or whether this is expected behaviour so I can include it in the report.
Depth image resolution is 320x240 at 30fps. I don't modify any of the calibration settings.

**Comment by ghindman** [comment]
What ROS package were you using to generate the map data, and is this issue reproducible outside of ROS?  It's difficult to tell if this is a ROS issue, or a librealsense issue with the data provided.

**Comment by imbachb** [comment]
What would be the simplest way to do this outside of ROS on Ubuntu? Is there an example program or something like that that outputs the depth in meters?

I hand the pointclouds from the realsense package over to the octomap package. The octomap cointains a modified stereo camera inverse sensor model to account for the measurement error distribution.
The error however was not only detected when using octomap. It's already present in the pointcloud generated by the realsense package.

**Comment by tripzero** [comment]
@imbachb can you ask this question to upstream librealsense?  I believe we are just forwarding the mean error data from librealsense.  They could probably give you better feedback on whether or not what you are seeing is expected behavior or not.
